[package]
name = "Originmate"
version = "3.0.0"
authors = [
    "David Lucid <david@pentagon.xyz>",
    "Jakub Labor <jakub@originbyte.io>",
    "Michael Bausano <michael@originbyte.io>",
    "Nuno Boavida <nuno@originbyte.io>"
]
published-at = "0xd151d7c3d24afee5f5df6e7c4ee7059c351b6e2dd59a9acc0fbf5e38390a32a5"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
# devnet-0.29.0
rev = "82c9c80c11488858f1d3930f47ec9f335a566683"

[addresses]
originmate = "0xd151d7c3d24afee5f5df6e7c4ee7059c351b6e2dd59a9acc0fbf5e38390a32a5"
